{
 "title": "COVID 19 - Portugal",
 "time": { "from": "2020-02-20T20:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   { "name": "regiao", "label": "Regiao", "query": "show field keys from obitos" }
  ]
 },
 "panels": [
  {
   "title": "Informação Geral",
   "type": "stat",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Confirmados",
     "measurement": "confirmados",
     "query": "SELECT mean(\"confirmados_portugal\") FROM \"confirmados\" WHERE $timeFilter GROUP BY time(1d)",
     "select": [
      [
       { "params": [ "confirmados_portugal" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Confirmados Activos",
     "measurement": "confirmados",
     "select": [
      [
       { "params": [ "confirmados_activos_portugal" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Obitos",
     "measurement": "obitos",
     "select": [
      [
       { "params": [ "obitos_portugal" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Recuperados",
     "measurement": "recuperados",
     "select": [
      [
       { "params": [ "recuperados_portugal" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Internados",
     "measurement": "geral",
     "select": [
      [
       { "params": [ "internados" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Internados UCI",
     "measurement": "geral",
     "select": [
      [
       { "params": [ "internados_uci" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Em Vigilância",
     "measurement": "geral",
     "select": [
      [
       { "params": [ "vigilancia" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Aguardam Resultado",
     "measurement": "geral",
     "select": [
      [
       { "params": [ "lab" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ultima Atualização",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "format": "dateTimeFromNow",
   "valueName": "last_time",
   "targets": [
    {
     "measurement": "confirmados",
     "select": [
      [
       { "params": [ "confirmados_portugal" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Google News - COVID 19",
   "type": "news",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Internados",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Internados",
     "measurement": "geral",
     "query": "SELECT \"internados\" FROM \"geral\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "internados" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Internados UCI",
     "measurement": "geral",
     "query": "SELECT \"internados_uci\" FROM \"geral\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "internados_uci" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Difrenca Diaria Internados UCI",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"internados_uci\") FROM \"geral\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Difrenca Diaria Internados",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT difference(\"internados\") FROM \"geral\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Confirmados - [[regiao]]",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Acumulado",
     "measurement": "confirmados",
     "query": "SELECT \"confirmados_[[regiao]]\" FROM \"confirmados\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "confirmados_portugal" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Diferenca Diaria",
     "measurement": "confirmados",
     "query": "SELECT difference(\"confirmados_[[regiao]]\") FROM \"confirmados\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "confirmados_portugal" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "Media Movel (7D)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT moving_average(\"value\", 7) FROM (SELECT difference(\"confirmados_[[regiao]]\") as \"value\" FROM \"confirmados\" WHERE $timeFilter)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Casos Activos - [[regiao]]",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Acumulado",
     "measurement": "confirmados",
     "query": "SELECT \"confirmados_activos_[[regiao]]\" FROM \"confirmados\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "confirmados_portugal" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Diferenca Diaria",
     "measurement": "confirmados",
     "query": "SELECT difference(\"confirmados_activos_[[regiao]]\") FROM \"confirmados\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "confirmados_portugal" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "Media Movel (7D)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT moving_average(\"value\", 7) FROM (SELECT difference(\"confirmados_activos_[[regiao]]\") as \"value\" FROM \"confirmados\" WHERE $timeFilter)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Obitos - [[regiao]]",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Acumulado",
     "measurement": "confirmados",
     "query": "SELECT \"obitos_[[regiao]]\" FROM \"obitos\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "confirmados_portugal" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Diferenca Diaria",
     "measurement": "confirmados",
     "query": "SELECT difference(\"obitos_[[regiao]]\") FROM \"obitos\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "confirmados_portugal" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "Media Movel (7D)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT moving_average(\"value\", 7) FROM (SELECT difference(\"obitos_[[regiao]]\") as \"value\" FROM \"obitos\" WHERE $timeFilter)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Recuperados - [[regiao]]",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Acumulado",
     "measurement": "confirmados",
     "query": "SELECT \"recuperados_[[regiao]]\" FROM \"recuperados\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "confirmados_portugal" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "Diferenca Diaria",
     "measurement": "confirmados",
     "query": "SELECT difference(\"recuperados_[[regiao]]\") FROM \"recuperados\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "confirmados_portugal" ], "type": "field" },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ]
    },
    {
     "alias": "Media Movel (7D)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT moving_average(\"value\", 7) FROM (SELECT difference(\"recuperados_[[regiao]]\") as \"value\" FROM \"recuperados\" WHERE $timeFilter)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}